// src/hooks/useEmailSeries.js - FIXED VERSION with proper state management
import { useState, useCallback } from 'react';
import { emailApi } from '../services/api';
import { useUsageTracking } from './useUsageTracking';

// Helper functions
const extractDomain = (url) => {
  try {
    const domain = url.replace(/(^\w+:|^)\/\//, '').split('/')[0];
    return domain.split('.').slice(-2, -1)[0] || domain;
  } catch {
    return 'website';
  }
};

const createSeriesNameFromDomain = (domain) => {
  return `${domain.charAt(0).toUpperCase() + domain.slice(1)} Email Series`;
};

/**
 * FIXED: Simplified email series hook that directly uses the email API
 * No more duplicate state management - this is the single source of truth for emailSeries
 */
export const useEmailSeries = ({
  extractedBenefits,
  selectedBenefits,
  websiteData,
  url,
  affiliateLink,
  tone,
  industry,
  exportFormat,
  currentEmailIndex,
  showToast,
  onGenerateComplete,
  user
}) => {

  console.log('🎯 useEmailSeries hook initialized - FIXED VERSION');
  
  // ✅ SINGLE SOURCE OF TRUTH for email series state
  const [emailSeries, setEmailSeries] = useState([]);
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Usage tracking
  const { trackEmailGeneration, trackSeriesCreated, trackAITokenUsage } = useUsageTracking();

  /**
   * ✅ FIXED: Direct API call with proper state management
   */
  const handleGenerateEmails = useCallback(async () => {
    const selectedBenefitsList = extractedBenefits.filter((_, index) => selectedBenefits[index]);
    
    if (selectedBenefitsList.length === 0) {
      showToast('Please select at least one benefit', 'error');
      return;
    }
    
    console.log('🚀 Starting email generation with selected benefits:', selectedBenefitsList);
    
    setIsGenerating(true);
    
    try {
      const domain = extractDomain(url);
      const userTier = user?.subscription_tier || 'free';
      
      showToast(`Generating ${selectedBenefitsList.length} emails with AI...`, 'info');
      
      // ✅ DIRECT API CALL - no intermediary state
      console.log('📡 Making direct API call to emailApi.generateEmails...');
      
      const result = await emailApi.generateEmails({
        benefits: selectedBenefitsList,
        selectedBenefits: selectedBenefitsList.map(() => true),
        websiteData: websiteData || {},
        tone: tone || 'persuasive',
        industry: industry || 'general',
        affiliateLink: affiliateLink || '',
        autoSave: true
      });
      
      console.log('✅ API Response received:', {
        success: result.success,
        emailCount: result.emails ? result.emails.length : 0,
        totalTokens: result.total_tokens
      });

      if (!result.success) {
        throw new Error(result.message || result.error || 'Failed to generate emails');
      }

      if (!result.emails || result.emails.length === 0) {
        throw new Error('No emails were generated by the API');
      }

      // ✅ PROCESS AND SET STATE DIRECTLY
      const emails = result.emails.map((email, index) => ({
        ...email,
        emailNumber: index + 1,
        createdAt: new Date().toISOString(),
        seriesName: createSeriesNameFromDomain(domain),
        domain,
        generatedWith: 'AI',
        userTier: userTier,
        aiModel: 'backend-api',
        readingLevel: '5th grade',
        isAffilateMarketing: true,
        qualityScore: userTier === 'gold' ? 'Premium' : userTier === 'pro' ? 'Professional' : 'Standard',
        generationMethod: 'Backend API'
      }));
      
      console.log('📧 Setting emailSeries state with processed emails:', emails.length);
      
      // ✅ THIS IS THE CRITICAL FIX - SET STATE IMMEDIATELY
      setEmailSeries(emails);
      
      // Track usage (non-blocking)
      try {
        await trackEmailGeneration(emails.length);
        await trackSeriesCreated(1);
        
        if (result.total_tokens > 0) {
          await trackAITokenUsage(result.total_tokens);
        }
        
        console.log('✅ Usage tracking completed');
      } catch (trackingError) {
        console.warn('⚠️ Usage tracking failed but continuing:', trackingError);
      }
      
      // Success message
      showToast(`🎉 Successfully generated ${emails.length} AI emails!`, 'success');
      
      // ✅ CALL COMPLETION CALLBACK WITH EMAILS
      if (onGenerateComplete) {
        console.log('🎯 Calling onGenerateComplete with emails...');
        onGenerateComplete({ emails });
      }
      
      console.log('✅ Email generation process completed successfully');
      
    } catch (error) {
      console.error('❌ Email generation error:', error);
      showToast(`Failed to generate emails: ${error.message}`, 'error');
      
      // ✅ ENSURE STATE IS CLEARED ON ERROR
      setEmailSeries([]);
    } finally {
      setIsGenerating(false);
      console.log('🔄 Generation process finished, isGenerating = false');
    }
  }, [
    extractedBenefits, 
    selectedBenefits, 
    websiteData, 
    url, 
    affiliateLink, 
    tone, 
    industry, 
    showToast, 
    onGenerateComplete,
    user,
    trackEmailGeneration,
    trackSeriesCreated,
    trackAITokenUsage
  ]);
  
  // Copy current email to clipboard
  const copyEmailToClipboard = useCallback(() => {
    if (emailSeries.length === 0) {
      console.warn('⚠️ No emails to copy - emailSeries is empty');
      return;
    }
    
    const email = emailSeries[currentEmailIndex];
    
    if (!email) {
      console.warn('⚠️ No email at current index:', currentEmailIndex);
      return;
    }
    
    try {
      let content = '';
      
      if (exportFormat === 'text') {
        content = `Subject: ${email.subject}\n\n${email.content || email.body}`;
      } else if (exportFormat === 'html') {
        content = `<h2>${email.subject}</h2>\n<div>${(email.content || email.body).replace(/\n/g, '<br>')}</div>`;
      } else if (exportFormat === 'markdown') {
        content = `# ${email.subject}\n\n${email.content || email.body}`;
      }
      
      navigator.clipboard.writeText(content);
      showToast(`Email copied to clipboard as ${exportFormat.toUpperCase()}!`, 'success');
    } catch (error) {
      console.error('❌ Error copying to clipboard:', error);
      showToast('Failed to copy to clipboard', 'error');
    }
  }, [emailSeries, currentEmailIndex, exportFormat, showToast]);
  
  // Handle export email
  const handleExportEmail = useCallback((format) => {
    if (emailSeries.length === 0) {
      console.warn('⚠️ No emails to export - emailSeries is empty');
      return;
    }
    
    const email = emailSeries[currentEmailIndex];
    
    if (!email) {
      console.warn('⚠️ No email at current index for export:', currentEmailIndex);
      return;
    }
    
    try {
      let content = '';
      let fileName = '';
      let mimeType = '';
      
      const metadata = `
Generated with: ${email.generationMethod || 'Backend API'}
User Tier: ${email.userTier || 'free'}
Quality Score: ${email.qualityScore || 'Standard'}
Reading Level: ${email.readingLevel || '5th grade'}
Created: ${new Date(email.createdAt).toLocaleDateString()}
Focus Benefit: ${email.benefit || 'Unknown'}`;
      
      if (format === 'pdf') {
        showToast('PDF export will be available in a future update', 'info');
        return;
      } else if (format === 'html') {
        content = `<!DOCTYPE html>
<html>
<head>
  <title>${email.subject}</title>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; max-width: 600px; margin: 0 auto; padding: 20px; }
    h1 { color: #333; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
    .email-body { white-space: pre-wrap; margin: 20px 0; }
    .email-meta { 
      font-size: 12px; 
      color: #666; 
      background: #f8f9fa;
      border: 1px solid #e9ecef;
      border-radius: 5px;
      padding: 15px; 
      margin-top: 30px; 
      white-space: pre-line;
    }
    .quality-badge {
      display: inline-block;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: bold;
      margin-right: 10px;
      background: #dcfce7;
      color: #166534;
    }
  </style>
</head>
<body>
  <h1>${email.subject}</h1>
  <div class="quality-badges">
    <span class="quality-badge">🤖 AI Generated</span>
  </div>
  <div class="email-body">${(email.content || email.body).replace(/\n/g, '<br>')}</div>
  <div class="email-meta">
    <strong>Email Metadata:</strong>${metadata}
  </div>
</body>
</html>`;
        fileName = `email-${email.emailNumber}-${email.domain}-ai.html`;
        mimeType = 'text/html';
      } else if (format === 'text') {
        content = `Subject: ${email.subject}\n\n${email.content || email.body}\n\n---\nEmail Metadata:${metadata}`;
        fileName = `email-${email.emailNumber}-${email.domain}-ai.txt`;
        mimeType = 'text/plain';
      } else if (format === 'markdown') {
        content = `# ${email.subject}\n\n${email.content || email.body}\n\n---\n**Email Metadata:**${metadata}`;
        fileName = `email-${email.emailNumber}-${email.domain}-ai.md`;
        mimeType = 'text/markdown';
      }
      
      // Create and download file
      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = fileName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      showToast(`Email exported as ${format.toUpperCase()}!`, 'success');
    } catch (error) {
      console.error(`❌ Error exporting as ${format}:`, error);
      showToast(`Failed to export as ${format}`, 'error');
    }
  }, [emailSeries, currentEmailIndex, showToast]);
  
  // ✅ DEBUG: Log state changes
  console.log('🔍 useEmailSeries state:', {
    emailSeriesLength: emailSeries.length,
    isGenerating,
    currentIndex: currentEmailIndex,
    hasEmails: emailSeries.length > 0
  });
  
  return {
    emailSeries,
    isGenerating,
    handleGenerateEmails,
    copyEmailToClipboard,
    handleExportEmail,
    userTier: user?.subscription_tier || 'free',
    aiAvailableForTier: true,
    generationStats: emailSeries.length > 0 ? {
      total: emailSeries.length,
      aiGenerated: emailSeries.length,
      templateFallback: 0,
      aiSuccessRate: 100
    } : null
  };
};