[phases.setup]
nixPkgs = ["python3", "ffmpeg-headless", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && python -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --timeout 600 --workers 1 --worker-class sync --max-requests 10 --preload app:app"

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"